# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Visualize"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "//github.com/christianmendoza/hugo-visualize-theme/blob/master/LICENSE.md"
description = "Visualize is a simple, one-page portfolio design with a fully functional lightbox."
homepage = "//github.com/christianmendoza/hugo-visualize-theme"
tags = ["minimal", "onepage", "one page", "responsive", "image", "gallery", "portfolio"]

features = []
min_version = "0.21"

[author]
  name = "Christian Mendoza"
  homepage = "//iamchristian.me"

# If porting an existing theme
[original]
  name = "TEMPLATED"
  homepage = "//templated.co/visualize"
  repo = ""
